# -*- coding: utf-8 -*-
"""Data Visualization _Practical Project _Code_09052026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYGZex1U1en8cN-oMIPqyCfoEecwjxvo
"""

!pip uninstall -y kaleido -q
!pip install -q kaleido==0.2.1

"""**1. Importing Libraries and Loading the Dataset**"""

# =========================================================
# Purpose: Import required libraries and upload the Excel dataset
# =========================================================

from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
import ipywidgets as widgets
from IPython.display import display, HTML
import warnings

# Clean output settings
warnings.filterwarnings("ignore")
pio.renderers.default = 'colab'

# Settings for clearer and more accessible visualisations later
TEMPLATE = "plotly_white"
COLOR_SEQ = px.colors.qualitative.Safe

uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)

"""**2. Dataset Structure and Data Types**"""

# =========================================================
# Purpose: Inspect the dataset structure and first records
# =========================================================

print("Dataset shape:", df.shape)
display(df.head())
display(df.columns)
df.info()

"""**3. Variable Overview and Summary Statistics**"""

# =========================================================
# Purpose: Review variable ranges, category values, and summary statistics for initial data understanding
# =========================================================

print("Date range:", df['Date'].min(), "to", df['Date'].max())

print("\nUnique cities:")
print(df['City'].unique())

print("\nNumber of cities:", df['City'].nunique())

print("\nUnique confectionary categories:")
print(df['Confectionary'].unique())

print("\nNumber of confectionary categories:", df['Confectionary'].nunique())

display(df.describe(include='all'))

"""**4. Data Quality Check Summary**"""

# =========================================================
# Purpose: Check missing values, duplicate rows, zero values, and negative values
# =========================================================

numeric_cols = ['Units Sold', 'Revenue(£)', 'Cost(£)', 'Profit(£)']

quality_summary = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Missing %': (df.isnull().sum() / len(df) * 100).round(2),
    'Zero Values': [((df[col] == 0).sum() if col in numeric_cols else np.nan) for col in df.columns],
    'Negative Values': [((df[col] < 0).sum() if col in numeric_cols else np.nan) for col in df.columns]
})

display(quality_summary)

print("Duplicate rows:", df.duplicated().sum())
print("Original dataset rows:", len(df))

"""**5. Dataset Size Before and After Cleaning**"""

# =========================================================
# Purpose: Remove missing values and duplicate rows, and report percentage removed
# =========================================================

original_rows = len(df)
original_shape = df.shape

df_clean = df.dropna().drop_duplicates().copy()

cleaned_rows = len(df_clean)
removed_rows = original_rows - cleaned_rows
removed_percentage = (removed_rows / original_rows) * 100

print("Original shape:", original_shape)
print("After removing missing values and duplicates:", df_clean.shape)
print("Rows removed:", removed_rows)
print(f"Percentage removed: {removed_percentage:.2f}%")

"""**6. Standardizing Confectionary Categories**"""

# =========================================================
# Purpose: Fix spelling and naming inconsistencies in confectionary categories
# =========================================================

df_clean['Confectionary'] = df_clean['Confectionary'].astype(str).str.strip()

df_clean['Confectionary'] = df_clean['Confectionary'].replace({
    'Caramel nut': 'Caramel Nut',
    'caramel nut': 'Caramel Nut',
    'CHOCOLATE CHUNK': 'Chocolate Chunk',
    'Chocolate chunk': 'Chocolate Chunk',
    'Choclate Chunk': 'Chocolate Chunk'
})

print("Cleaned confectionary categories:")
print(df_clean['Confectionary'].unique())

"""**7. Feature Engineering for Profitability and Dashboard Variables**"""

# =========================================================
# Purpose: Create derived fields for profitability analysis and dashboard use
# =========================================================

df_clean['Date'] = pd.to_datetime(df_clean['Date'])

country_map = {
    'London': 'United Kingdom',
    'Paris': 'France',
    'Bonn': 'Germany',
    'Seville': 'Spain',
    'Napoli': 'Italy'
}

city_lat_lon = {
    'London': {'Latitude': 51.5074, 'Longitude': -0.1278},
    'Paris': {'Latitude': 48.8566, 'Longitude': 2.3522},
    'Bonn': {'Latitude': 50.7374, 'Longitude': 7.0982},
    'Seville': {'Latitude': 37.3891, 'Longitude': -5.9845},
    'Napoli': {'Latitude': 40.8518, 'Longitude': 14.2681}
}

df_clean['Country'] = df_clean['City'].map(country_map)
df_clean['Latitude'] = df_clean['City'].map(lambda x: city_lat_lon[x]['Latitude'])
df_clean['Longitude'] = df_clean['City'].map(lambda x: city_lat_lon[x]['Longitude'])

df_clean['Year'] = df_clean['Date'].dt.year
df_clean['Month'] = df_clean['Date'].dt.month
df_clean['Month_Name'] = df_clean['Date'].dt.strftime('%b')

month_order = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
               'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

df_clean['Month_Name'] = pd.Categorical(
    df_clean['Month_Name'],
    categories=month_order,
    ordered=True
)

df_clean['Profit Margin (%)'] = (df_clean['Profit(£)'] / df_clean['Revenue(£)']) * 100
df_clean['Cost-to-Revenue Ratio (%)'] = (df_clean['Cost(£)'] / df_clean['Revenue(£)']) * 100
df_clean['Profit per Unit (£)'] = df_clean['Profit(£)'] / df_clean['Units Sold']

display(df_clean[
    ['Date', 'City', 'Country', 'Confectionary', 'Units Sold',
     'Revenue(£)', 'Cost(£)', 'Profit(£)', 'Profit Margin (%)',
     'Cost-to-Revenue Ratio (%)', 'Profit per Unit (£)']
].head())

display(df_clean[['Profit Margin (%)', 'Cost-to-Revenue Ratio (%)', 'Profit per Unit (£)']].describe())

"""**8. Final Validation of the Cleaned Dataset**"""

# =========================================================
# Purpose: Confirm final data quality after preprocessing and check profit consistency
# =========================================================

print("Final cleaned dataset shape:", df_clean.shape)

print("\nRemaining missing values:")
display(df_clean.isnull().sum())

print("\nRemaining duplicates:", df_clean.duplicated().sum())

final_quality = pd.DataFrame({
    'Zero Values': [
        (df_clean[col] == 0).sum() if col in ['Units Sold', 'Revenue(£)', 'Cost(£)', 'Profit(£)'] else np.nan
        for col in df_clean.columns
    ],
    'Negative Values': [
        (df_clean[col] < 0).sum() if col in ['Units Sold', 'Revenue(£)', 'Cost(£)', 'Profit(£)'] else np.nan
        for col in df_clean.columns
    ]
}, index=df_clean.columns)

display(final_quality)

# Check whether Profit is consistent with Revenue - Cost
df_clean['Calculated Profit (£)'] = df_clean['Revenue(£)'] - df_clean['Cost(£)']
df_clean['Profit Difference (£)'] = df_clean['Profit(£)'] - df_clean['Calculated Profit (£)']

print("\nProfit consistency check:")
display(df_clean['Profit Difference (£)'].describe())

inconsistent_profit_count = (df_clean['Profit Difference (£)'].abs() > 0.01).sum()
print("Rows where Profit does not match Revenue - Cost:", inconsistent_profit_count)

"""**9. Distribution of Numerical Variables**"""

# =========================================================
# Purpose: Visualise the distribution of key numerical and profitability variables
# =========================================================

distribution_cols = [
    'Units Sold',
    'Revenue(£)',
    'Cost(£)',
    'Profit(£)',
    'Profit Margin (%)',
    'Cost-to-Revenue Ratio (%)'
]

df_clean[distribution_cols].hist(
    figsize=(16, 12),
    bins=20
)

plt.suptitle('Distribution of Key Numerical and Profitability Variables', fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.96])

plt.savefig("figure_9_distribution_numerical_variables.png", dpi=300, bbox_inches="tight")
plt.show()

"""**10. Skewness Analysis**"""

# =========================================================
# Purpose: Measure skewness of key numerical and profitability variables
# =========================================================

skewness_results = df_clean[
    [
        'Units Sold',
        'Revenue(£)',
        'Cost(£)',
        'Profit(£)',
        'Profit Margin (%)',
        'Cost-to-Revenue Ratio (%)'
    ]
].skew().round(2)

display(skewness_results)

"""**11. Outlier Detection Using Boxplots**"""

# =========================================================
# Purpose: Detect outliers in key numerical and profitability variables
# =========================================================

outlier_cols = [
    'Units Sold',
    'Revenue(£)',
    'Cost(£)',
    'Profit(£)',
    'Profit Margin (%)',
    'Cost-to-Revenue Ratio (%)'
]

df_clean[outlier_cols].plot(
    kind='box',
    subplots=True,
    layout=(3, 2),
    figsize=(16, 12),
    sharex=False,
    sharey=False
)

plt.suptitle('Outlier Detection for Sales and Profitability Variables', fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.96])

plt.savefig("figure_11_outlier_detection_boxplots.png", dpi=300, bbox_inches="tight")
plt.show()

"""**12. Total Revenue by City**"""

# =========================================================
# Purpose: Analyse total revenue by city
# =========================================================

city_sales = df_clean.groupby(
    'City',
    as_index=False
)['Revenue(£)'].sum().sort_values('Revenue(£)', ascending=False)

display(city_sales)

fig_city = px.bar(
    city_sales,
    x='City',
    y='Revenue(£)',
    color='Revenue(£)',
    text='Revenue(£)',
    title='Total Revenue by City',
    labels={'Revenue(£)': 'Total Revenue (£)'},
    template=TEMPLATE
)

fig_city.update_traces(texttemplate='£%{text:,.0f}', textposition='outside')
fig_city.update_layout(width=1100, height=650)

fig_city.show()

# Save high-resolution image for Word report

fig_city.write_image("figure_12_total_revenue_by_city.png", width=1200, height=700, scale=2)
print("Figure 12 saved in Colab Files.")

"""**13. Total Profit by City**"""

# =========================================================
# Purpose: Analyse total profit by city to strengthen profitability-focused analysis
# =========================================================

city_profitability = df_clean.groupby(
    'City',
    as_index=False
).agg(
    Total_Revenue=('Revenue(£)', 'sum'),
    Total_Cost=('Cost(£)', 'sum'),
    Total_Profit=('Profit(£)', 'sum'),
    Average_Profit_Margin=('Profit Margin (%)', 'mean'),
    Cost_to_Revenue_Ratio=('Cost-to-Revenue Ratio (%)', 'mean'),
    Units_Sold=('Units Sold', 'sum')
).sort_values('Total_Profit', ascending=False)

display(city_profitability)

fig_city_profit = px.bar(
    city_profitability,
    x='City',
    y='Total_Profit',
    color='Total_Profit',
    text='Total_Profit',
    title='Total Profit by City',
    labels={'Total_Profit': 'Total Profit (£)'},
    template=TEMPLATE
)

fig_city_profit.update_traces(texttemplate='£%{text:,.0f}', textposition='outside')
fig_city_profit.update_layout(width=1100, height=650)

fig_city_profit.show()

# Save high-resolution image for Word report
try:
    fig_city_profit.write_image("figure_13_total_profit_by_city.png", width=1200, height=700, scale=2)
    print("Figure 13 saved in Colab Files.")
except Exception:
    print("Figure 13 displayed successfully. Image export was skipped.")

"""**14. Profit Margin and Cost-to-Revenue Ratio by City**"""

# =========================================================
# Purpose: Compare city-level profitability efficiency and cost pressure
# =========================================================

city_margin = city_profitability.sort_values('Average_Profit_Margin', ascending=False)

fig_city_margin = px.bar(
    city_margin,
    x='City',
    y='Average_Profit_Margin',
    color='City',
    text='Average_Profit_Margin',
    title='Average Profit Margin by City',
    labels={'Average_Profit_Margin': 'Average Profit Margin (%)'},
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_city_margin.update_traces(texttemplate='%{text:.2f}%', textposition='outside')
fig_city_margin.update_layout(width=1100, height=650, showlegend=False)

fig_city_margin.show()

try:
    fig_city_margin.write_image("figure_14_profit_margin_by_city.png", width=1200, height=700, scale=2)
    print("Figure 14a saved in Colab Files.")
except Exception:
    print("Figure 14a displayed successfully. Image export was skipped.")


fig_cost_ratio_city = px.bar(
    city_profitability.sort_values('Cost_to_Revenue_Ratio', ascending=False),
    x='City',
    y='Cost_to_Revenue_Ratio',
    color='City',
    text='Cost_to_Revenue_Ratio',
    title='Cost-to-Revenue Ratio by City',
    labels={'Cost_to_Revenue_Ratio': 'Cost-to-Revenue Ratio (%)'},
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_cost_ratio_city.update_traces(texttemplate='%{text:.2f}%', textposition='outside')
fig_cost_ratio_city.update_layout(width=1100, height=650, showlegend=False)

fig_cost_ratio_city.show()

try:
    fig_cost_ratio_city.write_image("figure_14_cost_to_revenue_by_city.png", width=1200, height=700, scale=2)
    print("Figure 14b saved in Colab Files.")
except Exception:
    print("Figure 14b displayed successfully. Image export was skipped.")

"""**15. Regional Confectionary Sales by Units Sold**"""

# =========================================================
# Purpose: Compare total units sold by country and confectionary type
# =========================================================

units_country_product = df_clean.groupby(
    ['Country', 'Confectionary'],
    as_index=False,
    observed=True
)['Units Sold'].sum()

display(units_country_product)

fig_units = px.bar(
    units_country_product,
    x='Country',
    y='Units Sold',
    color='Confectionary',
    barmode='group',
    title='Regional Confectionary Sales by Units Sold',
    labels={'Units Sold': 'Total Units Sold'},
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_units.update_layout(width=1100, height=650)

fig_units.show()

try:
    fig_units.write_image("figure_15_regional_confectionary_sales_units.png", width=1200, height=700, scale=2)
    print("Figure 15 saved in Colab Files.")
except Exception:
    print("Figure 15 displayed successfully. Image export was skipped.")

"""**16. Total Profit by Confectionary Type**"""

# =========================================================
# Purpose: Analyse total profit contribution by confectionary type
# =========================================================

product_profitability = df_clean.groupby(
    'Confectionary',
    as_index=False
).agg(
    Total_Revenue=('Revenue(£)', 'sum'),
    Total_Cost=('Cost(£)', 'sum'),
    Total_Profit=('Profit(£)', 'sum'),
    Average_Profit=('Profit(£)', 'mean'),
    Average_Profit_Margin=('Profit Margin (%)', 'mean'),
    Cost_to_Revenue_Ratio=('Cost-to-Revenue Ratio (%)', 'mean'),
    Units_Sold=('Units Sold', 'sum')
).sort_values('Total_Profit', ascending=False)

display(product_profitability)

fig_product_total_profit = px.bar(
    product_profitability,
    x='Confectionary',
    y='Total_Profit',
    color='Total_Profit',
    text='Total_Profit',
    title='Total Profit by Confectionary Type',
    labels={'Total_Profit': 'Total Profit (£)'},
    template=TEMPLATE
)

fig_product_total_profit.update_traces(texttemplate='£%{text:,.0f}', textposition='outside')
fig_product_total_profit.update_layout(width=1100, height=650)

fig_product_total_profit.show()

try:
    fig_product_total_profit.write_image("figure_16_total_profit_by_confectionary.png", width=1200, height=700, scale=2)
    print("Figure 16 saved in Colab Files.")
except Exception:
    print("Figure 16 displayed successfully. Image export was skipped.")

"""**17. Average Profit and Profit Margin by Confectionary Type**"""

# =========================================================
# Purpose: Compare product-level average profit and profit margin efficiency
# =========================================================

# Average profit by confectionary type
fig_product_avg_profit = px.bar(
    product_profitability.sort_values('Average_Profit', ascending=False),
    x='Confectionary',
    y='Average_Profit',
    color='Confectionary',
    text='Average_Profit',
    title='Average Profit by Confectionary Type',
    labels={'Average_Profit': 'Average Profit (£)'},
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_product_avg_profit.update_traces(texttemplate='£%{text:,.0f}', textposition='outside')
fig_product_avg_profit.update_layout(width=1100, height=650, showlegend=False)

fig_product_avg_profit.show()

try:
    fig_product_avg_profit.write_image("figure_17a_average_profit_by_confectionary.png", width=1200, height=700, scale=2)
    print("Figure 17a saved in Colab Files.")
except Exception:
    print("Figure 17a displayed successfully. Image export was skipped.")


# Average profit margin by confectionary type
fig_product_margin = px.bar(
    product_profitability.sort_values('Average_Profit_Margin', ascending=False),
    x='Confectionary',
    y='Average_Profit_Margin',
    color='Confectionary',
    text='Average_Profit_Margin',
    title='Average Profit Margin by Confectionary Type',
    labels={'Average_Profit_Margin': 'Average Profit Margin (%)'},
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_product_margin.update_traces(texttemplate='%{text:.2f}%', textposition='outside')
fig_product_margin.update_layout(width=1100, height=650, showlegend=False)

fig_product_margin.show()

try:
    fig_product_margin.write_image("figure_17b_profit_margin_by_confectionary.png", width=1200, height=700, scale=2)
    print("Figure 17b saved in Colab Files.")
except Exception:
    print("Figure 17b displayed successfully. Image export was skipped.")

"""**18. Product Profitability by Country**"""

# =========================================================
# Purpose: Compare total profit by confectionary type across countries
# =========================================================

profit_product_country = df_clean.groupby(
    ['Confectionary', 'Country'],
    as_index=False,
    observed=True
)['Profit(£)'].sum()

display(profit_product_country)

fig_product_country_profit = px.bar(
    profit_product_country,
    x='Confectionary',
    y='Profit(£)',
    color='Country',
    barmode='stack',
    text='Profit(£)',
    title='Product Profitability by Country',
    labels={'Profit(£)': 'Total Profit (£)'},
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_product_country_profit.update_traces(
    texttemplate='£%{text:,.0f}',
    textposition='inside'
)

fig_product_country_profit.update_layout(width=1100, height=650)

fig_product_country_profit.show()

try:
    fig_product_country_profit.write_image(
        "figure_18_product_profitability_by_country.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 18 saved in Colab Files.")
except Exception:
    print("Figure 18 displayed successfully. Image export was skipped.")

"""**19. Highest and Lowest Profit Margin by Country**"""

# =========================================================
# Purpose: Identify confectionary types with highest and lowest profit margin by country
# =========================================================

country_conf_margin = df_clean.groupby(
    ['Country', 'Confectionary'],
    as_index=False,
    observed=True
).agg(
    mean_margin=('Profit Margin (%)', 'mean'),
    profit_sum=('Profit(£)', 'sum'),
    revenue_sum=('Revenue(£)', 'sum'),
    records=('Date', 'count')
)

max_idx = country_conf_margin.groupby('Country')['mean_margin'].idxmax()
min_idx = country_conf_margin.groupby('Country')['mean_margin'].idxmin()

max_margin_country = country_conf_margin.loc[max_idx].assign(Type='Highest Profit Margin')
min_margin_country = country_conf_margin.loc[min_idx].assign(Type='Lowest Profit Margin')

combined_margin = pd.concat(
    [max_margin_country, min_margin_country],
    ignore_index=True
)

display(combined_margin.sort_values(['Country', 'Type']))

fig_margin_compare = px.bar(
    combined_margin,
    x='Country',
    y='mean_margin',
    color='Confectionary',
    facet_col='Type',
    text='mean_margin',
    barmode='group',
    title='Highest and Lowest Profit Margin Confectionary Type by Country',
    labels={'mean_margin': 'Average Profit Margin (%)'},
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_margin_compare.update_traces(
    texttemplate='%{text:.1f}%',
    textposition='outside'
)

fig_margin_compare.update_layout(width=1200, height=650)

fig_margin_compare.show()

try:
    fig_margin_compare.write_image(
        "figure_19_highest_lowest_profit_margin_by_country.png",
        width=1300,
        height=700,
        scale=2
    )
    print("Figure 19 saved in Colab Files.")
except Exception:
    print("Figure 19 displayed successfully. Image export was skipped.")

"""**20. Revenue vs Profit Bubble Chart**"""

# =========================================================
# Purpose: Analyse the relationship between revenue, profit, units sold, and city
# =========================================================

fig_bubble = px.scatter(
    df_clean,
    x='Revenue(£)',
    y='Profit(£)',
    size='Units Sold',
    color='City',
    hover_data=['Confectionary', 'Year', 'Profit Margin (%)'],
    title='Revenue vs Profit by City and Units Sold',
    labels={
        'Revenue(£)': 'Revenue (£)',
        'Profit(£)': 'Profit (£)',
        'Units Sold': 'Units Sold',
        'Profit Margin (%)': 'Profit Margin (%)'
    },
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_bubble.update_layout(width=1100, height=650)

fig_bubble.show()

try:
    fig_bubble.write_image(
        "figure_20_revenue_vs_profit_bubble_chart.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 20 saved in Colab Files.")
except Exception:
    print("Figure 20 displayed successfully. Image export was skipped.")

"""**21. Total Profit Over Time**"""

# =========================================================
# Purpose: Analyse annual profit trend over time
# =========================================================

yearly_profit = df_clean.groupby(
    'Year',
    as_index=False
).agg(
    Total_Revenue=('Revenue(£)', 'sum'),
    Total_Cost=('Cost(£)', 'sum'),
    Total_Profit=('Profit(£)', 'sum'),
    Average_Profit_Margin=('Profit Margin (%)', 'mean'),
    Cost_to_Revenue_Ratio=('Cost-to-Revenue Ratio (%)', 'mean')
)

display(yearly_profit)

fig_profit_time = px.line(
    yearly_profit,
    x='Year',
    y='Total_Profit',
    markers=True,
    title='Total Profit Over Time',
    labels={'Total_Profit': 'Total Profit (£)', 'Year': 'Year'},
    template=TEMPLATE
)

fig_profit_time.update_layout(width=1100, height=650)

fig_profit_time.show()

try:
    fig_profit_time.write_image(
        "figure_21_total_profit_over_time.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 21 saved in Colab Files.")
except Exception:
    print("Figure 21 displayed successfully. Image export was skipped.")

"""**22. Revenue Over Time**"""

# =========================================================
# Purpose: Analyse annual revenue trend over time
# =========================================================

yearly_sales = df_clean.groupby(
    'Year',
    as_index=False
)['Revenue(£)'].sum()

display(yearly_sales)

fig_time = px.line(
    yearly_sales,
    x='Year',
    y='Revenue(£)',
    markers=True,
    title='Revenue Over Time',
    labels={'Revenue(£)': 'Total Revenue (£)', 'Year': 'Year'},
    template=TEMPLATE
)

fig_time.update_layout(width=1100, height=650)

fig_time.show()

try:
    fig_time.write_image(
        "figure_22_revenue_over_time.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 22 saved in Colab Files.")
except Exception:
    print("Figure 22 displayed successfully. Image export was skipped.")

"""**23. Peak Revenue Month by Country**"""

# =========================================================
# Purpose: Identify the peak revenue month for each country
# =========================================================

df_peak = df_clean.copy()
df_peak['Year_Month'] = df_peak['Date'].dt.to_period('M').astype(str)

country_month_revenue = df_peak.groupby(
    ['Country', 'Year_Month'],
    as_index=False,
    observed=True
)['Revenue(£)'].sum()

peak_idx = country_month_revenue.groupby('Country')['Revenue(£)'].idxmax()
peak_revenue_month = country_month_revenue.loc[peak_idx].sort_values('Country')

display(peak_revenue_month)

fig_peak_month = px.bar(
    peak_revenue_month,
    x='Country',
    y='Revenue(£)',
    text='Year_Month',
    color='Country',
    title='Peak Revenue Month by Country',
    labels={'Revenue(£)': 'Peak Monthly Revenue (£)', 'Year_Month': 'Peak Month'},
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_peak_month.update_traces(textposition='outside')
fig_peak_month.update_layout(width=1100, height=650, showlegend=False)

fig_peak_month.show()

try:
    fig_peak_month.write_image(
        "figure_23_peak_revenue_month_by_country.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 23 saved in Colab Files.")
except Exception:
    print("Figure 23 displayed successfully. Image export was skipped.")

"""**24. Total Units Sold by Country**"""

# =========================================================
# Purpose: Compare total sales volume by country using units sold
# =========================================================

units_country = df_clean.groupby(
    'Country',
    as_index=False,
    observed=True
)['Units Sold'].sum().sort_values('Units Sold', ascending=True)

display(units_country)

fig_units_country = px.bar(
    units_country,
    x='Units Sold',
    y='Country',
    orientation='h',
    text='Units Sold',
    title='Total Units Sold by Country',
    labels={'Units Sold': 'Total Units Sold'},
    color='Units Sold',
    template=TEMPLATE
)

fig_units_country.update_traces(texttemplate='%{text:,.0f}', textposition='outside')
fig_units_country.update_layout(width=1100, height=650)

fig_units_country.show()

try:
    fig_units_country.write_image(
        "figure_24_total_units_sold_by_country.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 24 saved in Colab Files.")
except Exception:
    print("Figure 24 displayed successfully. Image export was skipped.")

"""**25. Profit Heatmap by City and Confectionary Type**"""

# =========================================================
# Purpose: Compare total profit across city and confectionary combinations
# =========================================================

city_product_profit = df_clean.groupby(
    ['City', 'Confectionary'],
    as_index=False,
    observed=True
).agg(
    Total_Revenue=('Revenue(£)', 'sum'),
    Total_Cost=('Cost(£)', 'sum'),
    Total_Profit=('Profit(£)', 'sum'),
    Average_Profit_Margin=('Profit Margin (%)', 'mean'),
    Cost_to_Revenue_Ratio=('Cost-to-Revenue Ratio (%)', 'mean'),
    Units_Sold=('Units Sold', 'sum')
)

display(city_product_profit.sort_values('Total_Profit', ascending=False))

profit_heatmap = city_product_profit.pivot_table(
    values='Total_Profit',
    index='City',
    columns='Confectionary',
    aggfunc='sum',
    observed=True
)

fig_profit_heatmap = px.imshow(
    profit_heatmap,
    text_auto='.0f',
    aspect='auto',
    title='Total Profit Heatmap by City and Confectionary Type',
    labels=dict(color='Total Profit (£)'),
    template=TEMPLATE
)

fig_profit_heatmap.update_layout(width=1100, height=650)

fig_profit_heatmap.show()

try:
    fig_profit_heatmap.write_image(
        "figure_25_profit_heatmap_city_confectionary.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 25 saved in Colab Files.")
except Exception:
    print("Figure 25 displayed successfully. Image export was skipped.")

"""**26. Lowest Profit Product-Location Combinations**"""

# =========================================================
# Purpose: Identify low-profit city and confectionary combinations for management review
# =========================================================

low_profit_combinations = city_product_profit.sort_values(
    'Total_Profit',
    ascending=True
).head(10)

display(low_profit_combinations)

fig_low_profit = px.bar(
    low_profit_combinations,
    x='Total_Profit',
    y='Confectionary',
    color='City',
    orientation='h',
    text='Total_Profit',
    title='Lowest Profit Product-Location Combinations',
    labels={
        'Total_Profit': 'Total Profit (£)',
        'Confectionary': 'Confectionary Type'
    },
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_low_profit.update_traces(
    texttemplate='£%{text:,.0f}',
    textposition='outside'
)

fig_low_profit.update_layout(width=1100, height=650)

fig_low_profit.show()

try:
    fig_low_profit.write_image(
        "figure_26_lowest_profit_product_location_combinations.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 26 saved in Colab Files.")
except Exception:
    print("Figure 26 displayed successfully. Image export was skipped.")

"""**27. City vs Product Revenue Heatmap**"""

# =========================================================
# Purpose: Compare average revenue by city and confectionary type
# =========================================================

city_product_revenue = df_clean.pivot_table(
    values='Revenue(£)',
    index='City',
    columns='Confectionary',
    aggfunc='mean',
    observed=True
)

display(city_product_revenue)

fig_city_product = px.imshow(
    city_product_revenue,
    text_auto='.0f',
    aspect='auto',
    title='City vs Product Average Revenue Heatmap',
    labels=dict(color='Average Revenue (£)'),
    template=TEMPLATE
)

fig_city_product.update_layout(width=1100, height=650)

fig_city_product.show()

try:
    fig_city_product.write_image(
        "figure_27_city_product_average_revenue_heatmap.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 27 saved in Colab Files.")
except Exception:
    print("Figure 27 displayed successfully. Image export was skipped.")

"""**28. Average Profit by Country**"""

# =========================================================
# Purpose: Analyse average profit by country
# =========================================================

avg_profit_country = df_clean.groupby(
    'Country',
    as_index=False,
    observed=True
)['Profit(£)'].mean().sort_values('Profit(£)', ascending=False)

display(avg_profit_country)

fig_avg_profit = px.bar(
    avg_profit_country,
    x='Country',
    y='Profit(£)',
    color='Country',
    text='Profit(£)',
    title='Average Profit by Country',
    labels={'Profit(£)': 'Average Profit (£)'},
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_avg_profit.update_traces(
    texttemplate='£%{text:,.0f}',
    textposition='outside'
)

fig_avg_profit.update_layout(width=1100, height=650, showlegend=False)

fig_avg_profit.show()

try:
    fig_avg_profit.write_image(
        "figure_28_average_profit_by_country.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 28 saved in Colab Files.")
except Exception:
    print("Figure 28 displayed successfully. Image export was skipped.")

"""**29. Profit Distribution by Country**"""

# =========================================================
# Purpose: Analyse the distribution, spread, and outliers of profit by country
# =========================================================

fig_profit_dist = px.box(
    df_clean,
    x='Country',
    y='Profit(£)',
    color='Country',
    points='all',
    title='Profit Distribution by Country',
    labels={'Profit(£)': 'Profit (£)'},
    color_discrete_sequence=COLOR_SEQ,
    template=TEMPLATE
)

fig_profit_dist.update_layout(width=1100, height=650, showlegend=False)

fig_profit_dist.show()

try:
    fig_profit_dist.write_image(
        "figure_29_profit_distribution_by_country.png",
        width=1200,
        height=700,
        scale=2
    )
    print("Figure 29 saved in Colab Files.")
except Exception:
    print("Figure 29 displayed successfully. Image export was skipped.")

"""**30. Correlation Matrix of Sales and Profitability Measures**"""

# =========================================================
# Purpose: Analyse correlation between numerical sales and profitability variables
# =========================================================

corr_cols = [
    'Units Sold',
    'Revenue(£)',
    'Cost(£)',
    'Profit(£)',
    'Profit Margin (%)',
    'Cost-to-Revenue Ratio (%)',
    'Profit per Unit (£)'
]

corr_matrix = df_clean[corr_cols].corr()

display(corr_matrix.round(2))

fig_corr = px.imshow(
    corr_matrix,
    text_auto='.2f',
    aspect='auto',
    title='Correlation Matrix of Sales and Profitability Measures',
    labels=dict(color='Correlation'),
    template=TEMPLATE
)

fig_corr.update_layout(width=1100, height=750)

fig_corr.show()

try:
    fig_corr.write_image(
        "figure_30_correlation_matrix_sales_profitability.png",
        width=1200,
        height=800,
        scale=2
    )
    print("Figure 30 saved in Colab Files.")
except Exception:
    print("Figure 30 displayed successfully. Image export was skipped.")

"""**31. European Profit Distribution Map**"""

# =========================================================
# Purpose: Create a European geographic visual of profit by city
# =========================================================

map_data = df_clean.groupby(
    ['City', 'Country', 'Latitude', 'Longitude'],
    as_index=False
).agg(
    Total_Revenue=('Revenue(£)', 'sum'),
    Total_Profit=('Profit(£)', 'sum'),
    Average_Profit_Margin=('Profit Margin (%)', 'mean'),
    Units_Sold=('Units Sold', 'sum')
)

display(map_data)

fig_europe_map = px.scatter_geo(
    map_data,
    lat='Latitude',
    lon='Longitude',
    size='Total_Profit',
    color='Average_Profit_Margin',
    text='City',
    hover_name='City',
    hover_data={
        'Country': True,
        'Total_Revenue': ':,.0f',
        'Total_Profit': ':,.0f',
        'Average_Profit_Margin': ':.2f',
        'Units_Sold': ':,.0f',
        'Latitude': False,
        'Longitude': False
    },
    title='European Bakery Profit Distribution by City',
    labels={
        'Average_Profit_Margin': 'Average Profit Margin (%)',
        'Total_Profit': 'Total Profit (£)'
    },
    color_continuous_scale='Viridis',
    size_max=35,
    template=TEMPLATE
)

fig_europe_map.update_traces(
    textposition='top center',
    marker=dict(
        line=dict(color='white', width=1.5),
        opacity=0.9
    )
)

fig_europe_map.update_geos(
    scope='europe',
    projection_type='natural earth',
    showland=True,
    landcolor='rgb(240, 240, 240)',
    showcountries=True,
    countrycolor='rgb(160, 160, 160)',
    showocean=True,
    oceancolor='rgb(220, 235, 247)',
    showlakes=True,
    lakecolor='rgb(220, 235, 247)',
    coastlinecolor='rgb(120, 120, 120)',
    fitbounds='locations'
)

fig_europe_map.update_layout(
    width=1150,
    height=750,
    title_x=0.5,
    margin=dict(l=20, r=20, t=70, b=20),
    coloraxis_colorbar=dict(
        title='Avg Margin (%)'
    )
)

fig_europe_map.show()

try:
    fig_europe_map.write_image(
        "figure_31_european_profit_distribution_map.png",
        width=1300,
        height=800,
        scale=2
    )
    print("Figure 31 saved in Colab Files.")
except Exception:
    print("Figure 31 displayed successfully. Image export was skipped.")

"""**32. Interactive European Profitability Dashboard**"""

# =========================================================
# Interactive European Profitability Dashboard
# Purpose: Create, display, filter, and save the dashboard
# Run this after Figure 31
# =========================================================

from IPython.display import clear_output
from html import escape

try:
    from google.colab import output
    output.enable_custom_widget_manager()
except Exception:
    pass

# -----------------------------
# Dashboard filters
# -----------------------------

country_filter_dash = widgets.Dropdown(
    options=['All'] + sorted(df_clean['Country'].dropna().unique().tolist()),
    value='All',
    description='Country:',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='220px')
)

year_filter_dash = widgets.Dropdown(
    options=['All'] + sorted(df_clean['Year'].dropna().unique().tolist()),
    value='All',
    description='Year:',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='180px')
)

product_filter_dash = widgets.SelectMultiple(
    options=sorted(df_clean['Confectionary'].dropna().unique().tolist()),
    value=tuple(sorted(df_clean['Confectionary'].dropna().unique().tolist())),
    description='Confectionary:',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='300px', height='140px')
)

# -----------------------------
# Helper functions
# -----------------------------

def filter_dashboard_data(country, year, products):
    dff = df_clean.copy()

    if country != 'All':
        dff = dff[dff['Country'] == country]

    if year != 'All':
        dff = dff[dff['Year'] == year]

    if products:
        dff = dff[dff['Confectionary'].isin(list(products))]

    return dff


def make_plot_html(fig, include_js=False):
    return fig.to_html(
        full_html=False,
        include_plotlyjs='cdn' if include_js else False,
        default_width='100%'
    )


def render_dashboard(country='All', year='All', products=None):
    if products is None:
        products = tuple(sorted(df_clean['Confectionary'].dropna().unique().tolist()))

    dff = filter_dashboard_data(country, year, products)

    if len(products) == 0:
        return "<b>Please select at least one confectionary type.</b>"

    if dff.empty:
        return "<b>No data available for the selected filters.</b>"

    total_revenue = dff['Revenue(£)'].sum()
    total_profit = dff['Profit(£)'].sum()
    avg_margin = dff['Profit Margin (%)'].mean()
    avg_cost_ratio = dff['Cost-to-Revenue Ratio (%)'].mean()
    total_units = dff['Units Sold'].sum()

    title_html = f"""
    <div style="text-align:center; margin:15px 0 20px 0;">
        <h2 style="color:#2c3e50; margin-bottom:6px;">
            European Bakery Profitability Dashboard
        </h2>
        <p style="color:#555; font-size:15px; margin-top:0;">
            Profit-focused dashboard filtered by country, year, and confectionary type
        </p>
        <p style="color:#777; font-size:13px;">
            Current view: <b>Country:</b> {country} |
            <b>Year:</b> {year} |
            <b>Products selected:</b> {len(products)}
        </p>
    </div>
    """

    kpi_html = f"""
    <div style="display:grid; grid-template-columns: repeat(5, 1fr); gap:12px; margin:10px 0 25px 0;">
        <div style="background:#1f77b4; padding:16px; border-radius:14px; text-align:center; color:white;">
            <h4>Total Revenue (£)</h4><h2>{total_revenue:,.0f}</h2>
        </div>
        <div style="background:#2ca02c; padding:16px; border-radius:14px; text-align:center; color:white;">
            <h4>Total Profit (£)</h4><h2>{total_profit:,.0f}</h2>
        </div>
        <div style="background:#ff7f0e; padding:16px; border-radius:14px; text-align:center; color:white;">
            <h4>Average Margin (%)</h4><h2>{avg_margin:.2f}%</h2>
        </div>
        <div style="background:#9467bd; padding:16px; border-radius:14px; text-align:center; color:white;">
            <h4>Cost-to-Revenue (%)</h4><h2>{avg_cost_ratio:.2f}%</h2>
        </div>
        <div style="background:#34495e; padding:16px; border-radius:14px; text-align:center; color:white;">
            <h4>Units Sold</h4><h2>{total_units:,.0f}</h2>
        </div>
    </div>
    """

    map_data_dash = dff.groupby(
        ['City', 'Country', 'Latitude', 'Longitude'],
        as_index=False
    ).agg(
        Total_Revenue=('Revenue(£)', 'sum'),
        Total_Profit=('Profit(£)', 'sum'),
        Average_Profit_Margin=('Profit Margin (%)', 'mean'),
        Units_Sold=('Units Sold', 'sum')
    )

    city_profit_dash = dff.groupby(
        'City',
        as_index=False
    )['Profit(£)'].sum().sort_values('Profit(£)', ascending=False)

    product_profit_dash = dff.groupby(
        'Confectionary',
        as_index=False
    )['Profit(£)'].sum().sort_values('Profit(£)', ascending=False)

    margin_dash = dff.groupby(
        'Confectionary',
        as_index=False
    )['Profit Margin (%)'].mean().sort_values('Profit Margin (%)', ascending=False)

    heatmap_dash = dff.pivot_table(
        values='Profit(£)',
        index='City',
        columns='Confectionary',
        aggfunc='sum',
        observed=True
    )

    trend_dash = dff.groupby(
        ['Year', 'Month', 'Month_Name'],
        as_index=False,
        observed=True
    )['Profit(£)'].sum().sort_values(['Year', 'Month'])

    fig_map = px.scatter_geo(
        map_data_dash,
        lat='Latitude',
        lon='Longitude',
        size='Total_Profit',
        color='Average_Profit_Margin',
        text='City',
        hover_name='City',
        hover_data={
            'Country': True,
            'Total_Revenue': ':,.0f',
            'Total_Profit': ':,.0f',
            'Average_Profit_Margin': ':.2f',
            'Units_Sold': ':,.0f',
            'Latitude': False,
            'Longitude': False
        },
        title='European Profit Distribution by City',
        labels={
            'Total_Profit': 'Total Profit (£)',
            'Average_Profit_Margin': 'Average Profit Margin (%)'
        },
        color_continuous_scale='Viridis',
        size_max=35,
        template=TEMPLATE
    )

    fig_map.update_traces(textposition='top center')
    fig_map.update_geos(
        scope='europe',
        projection_type='natural earth',
        showland=True,
        landcolor='rgb(240, 240, 240)',
        showcountries=True,
        countrycolor='rgb(160, 160, 160)',
        showocean=True,
        oceancolor='rgb(220, 235, 247)',
        fitbounds='locations'
    )
    fig_map.update_layout(height=560, title_x=0.5)

    fig_city = px.bar(
        city_profit_dash,
        x='City',
        y='Profit(£)',
        color='City',
        text='Profit(£)',
        title='Total Profit by City',
        labels={'Profit(£)': 'Total Profit (£)'},
        color_discrete_sequence=COLOR_SEQ,
        template=TEMPLATE
    )
    fig_city.update_traces(texttemplate='£%{text:,.0f}', textposition='outside')
    fig_city.update_layout(height=430, showlegend=False)

    fig_product = px.bar(
        product_profit_dash,
        x='Confectionary',
        y='Profit(£)',
        color='Confectionary',
        text='Profit(£)',
        title='Total Profit by Confectionary Type',
        labels={'Profit(£)': 'Total Profit (£)'},
        color_discrete_sequence=COLOR_SEQ,
        template=TEMPLATE
    )
    fig_product.update_traces(texttemplate='£%{text:,.0f}', textposition='outside')
    fig_product.update_layout(height=430, showlegend=False)

    fig_margin = px.bar(
        margin_dash,
        x='Confectionary',
        y='Profit Margin (%)',
        color='Confectionary',
        text='Profit Margin (%)',
        title='Average Profit Margin by Confectionary Type',
        labels={'Profit Margin (%)': 'Average Profit Margin (%)'},
        color_discrete_sequence=COLOR_SEQ,
        template=TEMPLATE
    )
    fig_margin.update_traces(texttemplate='%{text:.2f}%', textposition='outside')
    fig_margin.update_layout(height=430, showlegend=False)

    fig_heatmap = px.imshow(
        heatmap_dash,
        text_auto='.0f',
        aspect='auto',
        title='Profit Heatmap by City and Confectionary Type',
        labels=dict(color='Total Profit (£)'),
        template=TEMPLATE
    )
    fig_heatmap.update_layout(height=460)

    fig_trend = px.line(
        trend_dash,
        x='Month_Name',
        y='Profit(£)',
        color='Year',
        markers=True,
        title='Monthly Profit Trend by Year',
        labels={
            'Profit(£)': 'Total Profit (£)',
            'Month_Name': 'Month'
        },
        template=TEMPLATE
    )
    fig_trend.update_layout(height=460)

    tiles = [
        ("European Profit Distribution Map", make_plot_html(fig_map, include_js=True), True),
        ("Total Profit by City", make_plot_html(fig_city), False),
        ("Total Profit by Confectionary Type", make_plot_html(fig_product), False),
        ("Average Profit Margin by Product", make_plot_html(fig_margin), False),
        ("Profit Heatmap by City and Product", make_plot_html(fig_heatmap), False),
        ("Monthly Profit Trend", make_plot_html(fig_trend), True)
    ]

    tile_html = ""
    for title, chart_html, full_width in tiles:
        full_class = "grid-column:1/-1;" if full_width else ""
        tile_html += f"""
        <div style="{full_class} background:white; padding:14px; border-radius:16px;
                    box-shadow:0 3px 12px rgba(0,0,0,0.08);">
            <h3 style="text-align:center; color:#2c3e50;">{title}</h3>
            {chart_html}
        </div>
        """

    body_html = f"""
    <div style="background:#f8fafc; padding:20px; font-family:Arial, sans-serif;">
        <div style="max-width:1250px; margin:0 auto;">
            {title_html}
            {kpi_html}
            <div style="display:grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap:18px;">
                {tile_html}
            </div>
        </div>
    </div>
    """

    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>European Bakery Profitability Dashboard</title>
    </head>
    <body style="margin:0; background:#f8fafc;">
        {body_html}
    </body>
    </html>
    """

    return full_html


# -----------------------------
# Dashboard display and save
# -----------------------------

dashboard_output = widgets.Output()

update_dashboard_button = widgets.Button(
    description='Update Dashboard',
    button_style='success',
    layout=widgets.Layout(width='180px')
)

def update_dashboard_view(button=None):
    with dashboard_output:
        clear_output(wait=True)

        html = render_dashboard(
            country=country_filter_dash.value,
            year=year_filter_dash.value,
            products=tuple(product_filter_dash.value)
        )

        with open("/content/dashboard_current_view.html", "w", encoding="utf-8") as f:
            f.write(html)

        print("Dashboard saved as: /content/dashboard_current_view.html")

        display(HTML(f"""
        <iframe
            srcdoc="{escape(html)}"
            width="100%"
            height="1400"
            style="border:1px solid #ddd; border-radius:12px;">
        </iframe>
        """))

update_dashboard_button.on_click(update_dashboard_view)

display(HTML("<h3>Interactive Dashboard Filters</h3>"))
display(widgets.HBox([
    country_filter_dash,
    year_filter_dash,
    product_filter_dash,
    update_dashboard_button
]))
display(dashboard_output)

update_dashboard_view()
